#include "../../src/libs/assert.h"
#include "../../src/libs/backtrace.h"
#include "../../src/libs/convert.h"
#include "../../src/libs/exec_command.h"
#include "../../src/libs/file.h"
#include "../../src/libs/format_iterator.h"
#include "../../src/libs/mem.h"
#include "../../src/libs/meta_iterator.h"
#include "../../src/libs/print.h"
#include "../../src/libs/stack_alloc.h"
#include "../../src/libs/system_time.h"
#include "../../src/libs/time.h"

#include "../../src/libs/assert.c"
#include "../../src/libs/backtrace.c"
#include "../../src/libs/convert.c"
#include "../../src/libs/exec_command.c"
#include "../../src/libs/file.c"
#include "../../src/libs/format_iterator.c"
#include "../../src/libs/mem.c"
#include "../../src/libs/meta_iterator.c"
#include "../../src/libs/print.c"
#include "../../src/libs/stack_alloc.c"
#include "../../src/libs/system_time.c"
#include "../../src/libs/time.c"

#include "./minimake_script.h"
#include "./target_build.h"
#include "./target_c_dependencies.h"
#include "./target_execution_list.h"
#include "./target_timestamp.h"

#include "./minimake_script.c"
#include "./target_build.c"
#include "./target_c_dependencies.c"
#include "./target_execution_list.c"
#include "./target_timestamp.c"
#include "./minimake.c"
