name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clean
      run: rm -rf ./build && bash ./minimake.sh

    - name: Build tests
      run: ./build/minimake test
    
    - name: Run tests
      run: ./build/test
